[build]
functions = "functions"
command = "npm start"

[functions]
  included_files = ["!node_modules/.prisma/**"]

[[redirects]]
force = true
from = "/*"
status = 200
to = "/.netlify/functions/api/:splat"

